version: '3.8'
services:
  app:
    build: .
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    env_file: .env
  database:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dgputterpro
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

volumes:
  data:
