"""rename Session table to Drill table

Revision ID: 31f178ee4544
Revises: 9dd71e92c764
Create Date: 2021-10-25 15:10:39.560077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f178ee4544'
down_revision = '9dd71e92c764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('putt_distance', sa.Integer(), nullable=True),
    sa.Column('number_attempts', sa.Integer(), nullable=True),
    sa.Column('number_putts_made', sa.Integer(), nullable=True),
    sa.CheckConstraint('number_putts_made <= number_attempts'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drill_timestamp'), 'drill', ['timestamp'], unique=False)
    op.drop_index('ix_session_timestamp', table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('putt_distance', sa.INTEGER(), nullable=True),
    sa.Column('number_attempts', sa.INTEGER(), nullable=True),
    sa.Column('number_putts_made', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('number_putts_made <= number_attempts'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_timestamp', 'session', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_drill_timestamp'), table_name='drill')
    op.drop_table('drill')
    # ### end Alembic commands ###
