"""session table

Revision ID: 9dd71e92c764
Revises: 2dc73bc0fffc
Create Date: 2021-10-25 14:33:57.794882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd71e92c764'
down_revision = '2dc73bc0fffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('putt_distance', sa.Integer(), nullable=True),
    sa.Column('number_attempts', sa.Integer(), nullable=True),
    sa.Column('number_putts_made', sa.Integer(), nullable=True),
    sa.CheckConstraint('number_putts_made <= number_attempts'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_timestamp'), 'session', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_timestamp'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###
